version: '3.2'
networks:
  shoppping-list-net:
    driver: bridge
services:
  zookeeper-main:
    extends:
      file: kafka-docker/docker-compose.yml
      service: zookeeper
    networks:
      - shoppping-list-net
  kafka-main:
    extends:
      file: kafka-docker/docker-compose.yml
      service: kafka
    networks:
      - shoppping-list-net
  mysql-main:
    extends:
      file: mysql/docker-compose.yml
      service: mysql
    networks:
      - shoppping-list-net