version: '3.2'
networks:
  shoppping-list-net:
    driver: bridge
services:
  zookeeper:
    extends:
      file: kafka-docker/docker-compose.yml
      service: zookeeper
    networks:
      - shoppping-list-net
  kafka:
    extends:
      file: kafka-docker/docker-compose.yml
      service: kafka
    networks:
      - shoppping-list-net
  mysql:
    extends:
      file: mysql/docker-compose.yml
      service: mysql
    networks:
      - shoppping-list-net
  scrapers:
    extends:
      file: scrapers/docker-compose.yml
      service: scrapers
    networks:
      - shoppping-list-net